[package]
name = "kbve"
authors = ["kbve", "h0lybyte"]
version = "0.1.11"
edition = "2021"
license = "MIT"
description = "KBVE is an Axum and Diesel Boilerplate that helps produce backend APIs for micro services."
homepage = "https://kbve.com/"
repository = "https://github.com/KBVE/kbve/tree/main/packages/kbve"
readme = "README.md"
rust-version = "1.75"

[dependencies]
anyhow = "1.0"
ammonia = "3.3.0"
argon2 = "0.5.0"
async-trait = "0.1.74"
chrono = { version = "0.4.24", features = ["serde"] }
diesel = { version = "2.0.0", features = ["mysql", "chrono", "r2d2"] }
dotenvy = "0.15"
axum = "0.6.20"
axum-extra = { version = "0.7.2", features = ["cookie"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dashmap = "5.5.3"
jsonwebtoken = "8.3.0"
rand_core = { version = "0.6.4", features = ["std"] }
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0.52"
time = "0.3.30"
reqwest = { version = "0.11",  default-features = false, features = ["json", "rustls-tls"] }
tower = { version = "0.4.13", features = ["timeout"] }
tower-http = { version = "0.4.4", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
r2d2 = "0.8.9"
regex = "1.10.2"
once_cell = "1"
ulid = "1.1.0"
num-bigint = "0.4"
jedi = "0.1.4"