name: '[WIP] Portainer Depolyment'
description: 'An action to help manage the Portainer deployment'
inputs:
  token:
    description: 'Your Github Organization Token'
  portainer-api-key:
    description: 'Your Portainer API Key'
    required: true
  portainer-endpoint:
    description: 'Your Portainer Endpoint'
    default: '2'
  portainer-swarm-id:
    description: 'Your Portainer Swarm ID'
  portainer-stack-name:
    description: 'Your Portainer Stack Name'
  portainer-stack-definition:
    description: 'Your Stack Definitions'
  portainer-template-variables:
    description: 'Your Template Variables'
  portainer-image:
    description: 'Your Image'
  portainer-prune-stack:
    description: 'Do you want to Prune Stack?'
    required: false
    default: 'false'
  org:
    description: 'Your Github Organization Name'
    default: 'KBVE'


runs:
  using: 'composite'
  steps:
    - name: Portainer Init
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |

      curl -s -X POST "$PORTAINER_URL/api/endpoints/$ENDPOINT_ID/docker/stacks" \
        -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
        -H "Content-Type: multipart/form-data" \
        -F "file=@$DOCKER_COMPOSE_FILE" \
        -F "Name=name-of-your-stack" \
        -F "SwarmID=target-swarm-id" \
        -F "Env=ENV_VAR1=value1,ENV_VAR2=value2"0
